### ISSUE TITLE
Image processing error

### ISSUE THREAD

**Issue by zaach** [vladikoff/fxa-local-dev#5]
I'm getting this error when trying to upload a profile image:

```
profile-server PORT 1111-5 (out): fxa-profile-server.server.ERROR: summary {"code":500,"method":"post","errno":103,"path":"/v1/avatar/upload","agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:35.0) Gecko/20100101 Firefox/35.0","t":10,"stack":"Error: Image processing error\n    at Function.processingError (/Users/zcarter/moz/fxa-local-dev/fxa-profile-server/lib/error.js:114:10)\n    at Request._callback (/Users/zcarter/moz/fxa-local-dev/fxa-profile-server/lib/routes/avatar/upload.js:38:25)\n    at self.callback (/Users/zcarter/moz/fxa-local-dev/fxa-profile-server/node_modules/request/request.js:372:22)\n    at Request.EventEmitter.emit (events.js:117:20)\n    at Request.onRequestError (/Users/zcarter/moz/fxa-local-dev/fxa-profile-server/node_modules/request/request.js:963:8)\n    at ClientRequest.EventEmitter.emit (events.js:95:17)\n    at Socket.socketErrorListener (http.js:1547:9)\n    at Socket.EventEmitter.emit (events.js:95:17)\n    at net.js:440:14\n    at process._tickDomainCallback (node.js:459:13)"}
```

Is there anything I need to run beyond `npm install`? FWIW I was able to upload images in my previous setup running all the servers manually.

**Comment by vladikoff** [comment]
Fixed. The profile worker was missing, just `git pull` on this repo and servers should work properly.

**Comment by vladikoff** [comment]
![image](https://cloud.githubusercontent.com/assets/128755/5665527/1af022ce-9727-11e4-9fa8-0586b98c13cb.png)
